general {
    lock_cmd = pidof hyprlock || hyprlock
}

# 5 min
listener {
    timeout = 300
    on-timeout = brightnessctl -s set 30%
    on-resume = brightnessctl -r
}

# 9.5 min
listener {
    timeout = 540
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# 10 min
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 15 min
listener {
    timeout = 900
    on-timeout = loginctl lock-session && systemd-run --user --unit=autoshutdown --on-active=900 /usr/bin/systemctl poweroff
    on-resume = systemctl --user stop autoshutdown 2>/dev/null
}
