foreground              #dde4e3
background              #0e1415
selection_foreground    #003738
selection_background    #80d4d7

cursor                  #80d4d7
cursor_text_color       #003738

url_color               #b4c7e9

active_tab_foreground   #9cf1f4
active_tab_background   #004f52
inactive_tab_foreground #bec8c8
inactive_tab_background #3f4949

color0  #0e1415
color1  #ffb4ab
color2  #b4c7e9
color3  #b0cccc
color4  #80d4d7
color5  #354763
color6  #d5e3ff
color7  #dde4e3
color8  #899393
color9  #93000a
color10 #354763
color11 #324b4c
color12 #004f52
color13 #1e314c
color14 #cce8e8
color15 #dde4e3
