foreground              #f1dfda
background              #1a110f
selection_foreground    #561f0f
selection_background    #ffb5a0

cursor                  #ffb5a0
cursor_text_color       #561f0f

url_color               #d8c58d

active_tab_foreground   #ffdbd1
active_tab_background   #723523
inactive_tab_foreground #d8c2bc
inactive_tab_background #53433f

color0  #1a110f
color1  #ffb4ab
color2  #d8c58d
color3  #e7bdb2
color4  #ffb5a0
color5  #524619
color6  #f5e1a7
color7  #f1dfda
color8  #a08c87
color9  #93000a
color10 #524619
color11 #5d4037
color12 #723523
color13 #3b2f05
color14 #ffdbd1
color15 #f1dfda
