monitor=,preferred,auto,1.07

$terminal = kitty
$launcher = rofi -show drun 

exec-once = hyprlock --inmediate
exec-once = waybar
exec-once = hypridle
exec-once = hyprsunset
exec-once = blueman-applet
exec-once = mako
exec-once = wl-paste --type text --watch cliphist store
exec-once = dbus-update-activation-enviroment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = GDK_BACKEND,wayland

input {
    kb_layout = es
    follow_mouse = 1
    accel_profile = flat
    sensitivity = 0

    touchpad {
        natural_scroll = true
        tap-to-click = true
    }

    touchdevice {
        transform = 0
    }

    tablet {
        transform = 0
    }
}

animations {
    enabled = false
}

decoration {
    blur {
        enabled = false
    }
    shadow {
        enabled = false
    }
}

misc {
    vfr = true
}

$mod = SUPER 

bind = $mod, Return, exec, $terminal
bind = $mod, Space, exec, $launcher
bind = $mod, q, killactive
bind = $mod, f, fullscreen
bind = $mod, l, exec, hyprlock

bind = $mod, V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy

bind = $mod, h, movefocus, l
bind = $mod, l, movefocus, r
bind = $mod, k, movefocus, u
bind = $mod, j, movefocus, d

bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, L, movewindow, r
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, J, movewindow, d

bind = Shift Super , S , exec, grim ~/screenshots/screenshot_$(date +%Y%m%d_%H%M%S).png

bind = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

bind = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
bind = $mod, XF86MonBrightnessUp, exec, hyprctl hyprsunset temperature -500
bind = $mod, XF86MonBrightnessDown, exec, hyprctl hyprsunset temperature +500 
